<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.audit</groupId>
        <artifactId>saas-common</artifactId>
        <version>2.5.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>saas-common-web</artifactId>

    <description>
        audit-common-web通信模块
    </description>

    <dependencies>

        <!-- Mysql Connector -->
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>

        <!-- 权限范围 -->
        <dependency>
            <groupId>com.audit</groupId>
            <artifactId>saas-common-datascope</artifactId>
        </dependency>

        <!-- audit Common DataSource -->
        <dependency>
            <groupId>com.audit</groupId>
            <artifactId>saas-common-datasource</artifactId>
        </dependency>

        <!-- audit Common DataSource -->
        <dependency>
            <groupId>com.audit</groupId>
            <artifactId>saas-common-seata</artifactId>
        </dependency>

    </dependencies>

</project>
